apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupConfig
metadata:
  name: team-onboarding
spec:
  labelSelector:
    matchLabels:
      type: devproject    
  templates:
    objectTemplate: |
      - apiVersion: v1
        kind: Namespace
        metadata:
          annotations:
            ncoCreatedOn: '{{ (lookup "v1" "Namespace" "" "namespace-configuration-operator").metadata.creationTimestamp }}'
            sourceTemplate: "{{ toYaml . | b64enc }}"
          name: {{ .Name | lower }}