apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupConfig
metadata:
  name: team-onboarding
spec:
  labelSelector:
    matchLabels:
      type: devproject
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{ index .Labels "teamname" }}-dev
          labels:
            team: {{ index .Labels "teamname" }}
            size: large
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: {{ index .Labels "teamname" }}-dev-admins
          namespace: {{ index .Labels "teamname" }}-dev
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: admin
        subjects:
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: {{ .Name }}